// Export all hooks from a single file for easier imports
export { useToast } from './use-toast';
export { useAuth } from '@/contexts/AuthContext';
export { useIsMobile } from './use-mobile';
export { useTestimonials } from './useTestimonials';
export { useHeroSettings } from './useHeroSettings';
export { useBenefits } from './useBenefits';
export { useForecastData } from './useForecastData';
export { useUnifiedRecruitmentMetrics } from './useUnifiedRecruitmentMetrics';
export { useActiveCustodians } from './useActiveCustodians';
export { useCustomerLTV } from './useCustomerLTV';
export { useROIMarketingDetails } from './useROIMarketingDetails';
export { useROIMarketingMonthly } from './useROIMarketingMonthly';
export { useRecruitmentMonthlyMetrics } from './useRecruitmentMonthlyMetrics';
export { useCallCenterMetrics } from './useCallCenterMetrics';
export { useCurrencyConverter } from './useCurrencyConverter';
export { useProgramacionInstalaciones } from './useProgramacionInstalaciones';
export { useEmpresasInstaladora } from './useEmpresasInstaladora';
export { useServiceCapacity } from './useServiceCapacity';
export { useArmedGuardsWithTracking } from './useArmedGuardsWithTracking';
export { useArmedGuardsOperativos } from './useArmedGuardsOperativos';
export { useProveedoresArmados } from './useProveedoresArmados';
export { usePredefinedMeetingPoints, useCreateMeetingPoint, useUpdateMeetingPoint, useDeleteMeetingPoint } from './usePredefinedMeetingPoints';
