
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TODO: Actualizar con las credenciales del proyecto Detecta
const SUPABASE_URL = "https://[PROJECT-ID].supabase.co"; // Reemplazar con la URL de Detecta
const SUPABASE_PUBLISHABLE_KEY = "YOUR_DETECTA_ANON_KEY"; // Reemplazar con la clave anon de Detecta

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
